/*
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fi.metatavu.metamind.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.metatavu.metamind.client.model.Coordinates;
import fi.metatavu.metamind.client.model.KnotType;
import fi.metatavu.metamind.client.model.TokenizerType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.UUID;

/**
 * ExportedStoryKnot
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-10T13:55:11.126+02:00[Europe/Helsinki]")public class ExportedStoryKnot {

  @JsonProperty("id")

  private UUID id = null;

  @JsonProperty("type")

  private KnotType type = null;

  @JsonProperty("tokenizer")

  private TokenizerType tokenizer = null;

  @JsonProperty("name")

  private String name = null;

  @JsonProperty("content")

  private String content = null;

  @JsonProperty("hint")

  private String hint = null;

  @JsonProperty("coordinates")

  private Coordinates coordinates = null;
  public ExportedStoryKnot id(UUID id) {
    this.id = id;
    return this;
  }

  

  /**
  * knot id.
  * @return id
  **/
  @Schema(description = "knot id.")
  public UUID getId() {
    return id;
  }
  public void setId(UUID id) {
    this.id = id;
  }
  public ExportedStoryKnot type(KnotType type) {
    this.type = type;
    return this;
  }

  

  /**
  * Get type
  * @return type
  **/
  @Schema(required = true, description = "")
  public KnotType getType() {
    return type;
  }
  public void setType(KnotType type) {
    this.type = type;
  }
  public ExportedStoryKnot tokenizer(TokenizerType tokenizer) {
    this.tokenizer = tokenizer;
    return this;
  }

  

  /**
  * Get tokenizer
  * @return tokenizer
  **/
  @Schema(required = true, description = "")
  public TokenizerType getTokenizer() {
    return tokenizer;
  }
  public void setTokenizer(TokenizerType tokenizer) {
    this.tokenizer = tokenizer;
  }
  public ExportedStoryKnot name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public ExportedStoryKnot content(String content) {
    this.content = content;
    return this;
  }

  

  /**
  * Get content
  * @return content
  **/
  @Schema(required = true, description = "")
  public String getContent() {
    return content;
  }
  public void setContent(String content) {
    this.content = content;
  }
  public ExportedStoryKnot hint(String hint) {
    this.hint = hint;
    return this;
  }

  

  /**
  * Get hint
  * @return hint
  **/
  @Schema(description = "")
  public String getHint() {
    return hint;
  }
  public void setHint(String hint) {
    this.hint = hint;
  }
  public ExportedStoryKnot coordinates(Coordinates coordinates) {
    this.coordinates = coordinates;
    return this;
  }

  

  /**
  * Get coordinates
  * @return coordinates
  **/
  @Schema(description = "")
  public Coordinates getCoordinates() {
    return coordinates;
  }
  public void setCoordinates(Coordinates coordinates) {
    this.coordinates = coordinates;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExportedStoryKnot exportedStoryKnot = (ExportedStoryKnot) o;
    return Objects.equals(this.id, exportedStoryKnot.id) &&
        Objects.equals(this.type, exportedStoryKnot.type) &&
        Objects.equals(this.tokenizer, exportedStoryKnot.tokenizer) &&
        Objects.equals(this.name, exportedStoryKnot.name) &&
        Objects.equals(this.content, exportedStoryKnot.content) &&
        Objects.equals(this.hint, exportedStoryKnot.hint) &&
        Objects.equals(this.coordinates, exportedStoryKnot.coordinates);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, type, tokenizer, name, content, hint, coordinates);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExportedStoryKnot {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    tokenizer: ").append(toIndentedString(tokenizer)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    hint: ").append(toIndentedString(hint)).append("\n");
    sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
