/*
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fi.metatavu.metamind.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ExportedStoryScript
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-10T13:55:11.126+02:00[Europe/Helsinki]")public class ExportedStoryScript {

  @JsonProperty("name")

  private String name = null;

  @JsonProperty("version")

  private String version = null;

  @JsonProperty("language")

  private String language = null;

  @JsonProperty("content")

  private String content = null;
  public ExportedStoryScript name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Script name
  * @return name
  **/
  @Schema(required = true, description = "Script name")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public ExportedStoryScript version(String version) {
    this.version = version;
    return this;
  }

  

  /**
  * Script version
  * @return version
  **/
  @Schema(required = true, description = "Script version")
  public String getVersion() {
    return version;
  }
  public void setVersion(String version) {
    this.version = version;
  }
  public ExportedStoryScript language(String language) {
    this.language = language;
    return this;
  }

  

  /**
  * Script language
  * @return language
  **/
  @Schema(required = true, description = "Script language")
  public String getLanguage() {
    return language;
  }
  public void setLanguage(String language) {
    this.language = language;
  }
  public ExportedStoryScript content(String content) {
    this.content = content;
    return this;
  }

  

  /**
  * Script content
  * @return content
  **/
  @Schema(required = true, description = "Script content")
  public String getContent() {
    return content;
  }
  public void setContent(String content) {
    this.content = content;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExportedStoryScript exportedStoryScript = (ExportedStoryScript) o;
    return Objects.equals(this.name, exportedStoryScript.name) &&
        Objects.equals(this.version, exportedStoryScript.version) &&
        Objects.equals(this.language, exportedStoryScript.language) &&
        Objects.equals(this.content, exportedStoryScript.content);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(name, version, language, content);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExportedStoryScript {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
