/*
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fi.metatavu.metamind.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.metatavu.metamind.client.model.VariableType;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ExportedStoryVariable
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-10T13:55:11.126+02:00[Europe/Helsinki]")public class ExportedStoryVariable {

  @JsonProperty("name")

  private String name = null;

  @JsonProperty("type")

  private VariableType type = null;

  @JsonProperty("validationScript")

  private String validationScript = null;
  public ExportedStoryVariable name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public ExportedStoryVariable type(VariableType type) {
    this.type = type;
    return this;
  }

  

  /**
  * Get type
  * @return type
  **/
  @Schema(required = true, description = "")
  public VariableType getType() {
    return type;
  }
  public void setType(VariableType type) {
    this.type = type;
  }
  public ExportedStoryVariable validationScript(String validationScript) {
    this.validationScript = validationScript;
    return this;
  }

  

  /**
  * Validation script
  * @return validationScript
  **/
  @Schema(description = "Validation script")
  public String getValidationScript() {
    return validationScript;
  }
  public void setValidationScript(String validationScript) {
    this.validationScript = validationScript;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExportedStoryVariable exportedStoryVariable = (ExportedStoryVariable) o;
    return Objects.equals(this.name, exportedStoryVariable.name) &&
        Objects.equals(this.type, exportedStoryVariable.type) &&
        Objects.equals(this.validationScript, exportedStoryVariable.validationScript);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(name, type, validationScript);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExportedStoryVariable {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    validationScript: ").append(toIndentedString(validationScript)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
