/*
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fi.metatavu.metamind.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.UUID;

/**
 * IntentTrainingMaterials
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-20T15:24:44.194+03:00[Europe/Helsinki]")public class IntentTrainingMaterials {

  @JsonProperty("intentOpenNlpDoccatId")

  private UUID intentOpenNlpDoccatId = null;

  @JsonProperty("intentRegexId")

  private UUID intentRegexId = null;

  @JsonProperty("variableOpenNlpNerId")

  private UUID variableOpenNlpNerId = null;

  @JsonProperty("variableOpenNlpRegex")

  private UUID variableOpenNlpRegex = null;
  public IntentTrainingMaterials intentOpenNlpDoccatId(UUID intentOpenNlpDoccatId) {
    this.intentOpenNlpDoccatId = intentOpenNlpDoccatId;
    return this;
  }

  

  /**
  * Intent OpenNLP Doccat training material id
  * @return intentOpenNlpDoccatId
  **/
  @Schema(description = "Intent OpenNLP Doccat training material id")
  public UUID getIntentOpenNlpDoccatId() {
    return intentOpenNlpDoccatId;
  }
  public void setIntentOpenNlpDoccatId(UUID intentOpenNlpDoccatId) {
    this.intentOpenNlpDoccatId = intentOpenNlpDoccatId;
  }
  public IntentTrainingMaterials intentRegexId(UUID intentRegexId) {
    this.intentRegexId = intentRegexId;
    return this;
  }

  

  /**
  * Intent regex training material id
  * @return intentRegexId
  **/
  @Schema(description = "Intent regex training material id")
  public UUID getIntentRegexId() {
    return intentRegexId;
  }
  public void setIntentRegexId(UUID intentRegexId) {
    this.intentRegexId = intentRegexId;
  }
  public IntentTrainingMaterials variableOpenNlpNerId(UUID variableOpenNlpNerId) {
    this.variableOpenNlpNerId = variableOpenNlpNerId;
    return this;
  }

  

  /**
  * Variable OpenNLP NER training material id
  * @return variableOpenNlpNerId
  **/
  @Schema(description = "Variable OpenNLP NER training material id")
  public UUID getVariableOpenNlpNerId() {
    return variableOpenNlpNerId;
  }
  public void setVariableOpenNlpNerId(UUID variableOpenNlpNerId) {
    this.variableOpenNlpNerId = variableOpenNlpNerId;
  }
  public IntentTrainingMaterials variableOpenNlpRegex(UUID variableOpenNlpRegex) {
    this.variableOpenNlpRegex = variableOpenNlpRegex;
    return this;
  }

  

  /**
  * Variable OpenNLP Regex training material id
  * @return variableOpenNlpRegex
  **/
  @Schema(description = "Variable OpenNLP Regex training material id")
  public UUID getVariableOpenNlpRegex() {
    return variableOpenNlpRegex;
  }
  public void setVariableOpenNlpRegex(UUID variableOpenNlpRegex) {
    this.variableOpenNlpRegex = variableOpenNlpRegex;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntentTrainingMaterials intentTrainingMaterials = (IntentTrainingMaterials) o;
    return Objects.equals(this.intentOpenNlpDoccatId, intentTrainingMaterials.intentOpenNlpDoccatId) &&
        Objects.equals(this.intentRegexId, intentTrainingMaterials.intentRegexId) &&
        Objects.equals(this.variableOpenNlpNerId, intentTrainingMaterials.variableOpenNlpNerId) &&
        Objects.equals(this.variableOpenNlpRegex, intentTrainingMaterials.variableOpenNlpRegex);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(intentOpenNlpDoccatId, intentRegexId, variableOpenNlpNerId, variableOpenNlpRegex);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntentTrainingMaterials {\n");
    
    sb.append("    intentOpenNlpDoccatId: ").append(toIndentedString(intentOpenNlpDoccatId)).append("\n");
    sb.append("    intentRegexId: ").append(toIndentedString(intentRegexId)).append("\n");
    sb.append("    variableOpenNlpNerId: ").append(toIndentedString(variableOpenNlpNerId)).append("\n");
    sb.append("    variableOpenNlpRegex: ").append(toIndentedString(variableOpenNlpRegex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
