/*
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fi.metatavu.metamind.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Script
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-06T11:54:34.480+03:00[Europe/Helsinki]")public class Script {

  @JsonProperty("id")

  private UUID id = null;

  @JsonProperty("name")

  private String name = null;

  @JsonProperty("version")

  private String version = null;

  @JsonProperty("language")

  private String language = null;

  @JsonProperty("content")

  private String content = null;

  @JsonProperty("createdAt")

  private OffsetDateTime createdAt = null;

  @JsonProperty("modifiedAt")

  private OffsetDateTime modifiedAt = null;
  /**
  * Script id
  * @return id
  **/
  @Schema(description = "Script id")
  public UUID getId() {
    return id;
  }
  public Script name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Script name
  * @return name
  **/
  @Schema(required = true, description = "Script name")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public Script version(String version) {
    this.version = version;
    return this;
  }

  

  /**
  * Script version
  * @return version
  **/
  @Schema(required = true, description = "Script version")
  public String getVersion() {
    return version;
  }
  public void setVersion(String version) {
    this.version = version;
  }
  public Script language(String language) {
    this.language = language;
    return this;
  }

  

  /**
  * Script language
  * @return language
  **/
  @Schema(required = true, description = "Script language")
  public String getLanguage() {
    return language;
  }
  public void setLanguage(String language) {
    this.language = language;
  }
  public Script content(String content) {
    this.content = content;
    return this;
  }

  

  /**
  * Script content
  * @return content
  **/
  @Schema(required = true, description = "Script content")
  public String getContent() {
    return content;
  }
  public void setContent(String content) {
    this.content = content;
  }
  /**
  * Creation time
  * @return createdAt
  **/
  @Schema(description = "Creation time")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }
  /**
  * Last modification time
  * @return modifiedAt
  **/
  @Schema(description = "Last modification time")
  public OffsetDateTime getModifiedAt() {
    return modifiedAt;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Script script = (Script) o;
    return Objects.equals(this.id, script.id) &&
        Objects.equals(this.name, script.name) &&
        Objects.equals(this.version, script.version) &&
        Objects.equals(this.language, script.language) &&
        Objects.equals(this.content, script.content) &&
        Objects.equals(this.createdAt, script.createdAt) &&
        Objects.equals(this.modifiedAt, script.modifiedAt);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, name, version, language, content, createdAt, modifiedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Script {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
