/*
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fi.metatavu.metamind.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.metatavu.metamind.client.model.TrainingMaterialType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * TrainingMaterial
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-06T06:19:40.155+03:00[Europe/Helsinki]")public class TrainingMaterial {

  @JsonProperty("id")

  private UUID id = null;

  @JsonProperty("type")

  private TrainingMaterialType type = null;

  @JsonProperty("storyId")

  private UUID storyId = null;

  @JsonProperty("text")

  private String text = null;

  @JsonProperty("name")

  private String name = null;

  @JsonProperty("createdAt")

  private OffsetDateTime createdAt = null;

  @JsonProperty("modifiedAt")

  private OffsetDateTime modifiedAt = null;
  /**
  * intent id.
  * @return id
  **/
  @Schema(description = "intent id.")
  public UUID getId() {
    return id;
  }
  public TrainingMaterial type(TrainingMaterialType type) {
    this.type = type;
    return this;
  }

  

  /**
  * Get type
  * @return type
  **/
  @Schema(description = "")
  public TrainingMaterialType getType() {
    return type;
  }
  public void setType(TrainingMaterialType type) {
    this.type = type;
  }
  public TrainingMaterial storyId(UUID storyId) {
    this.storyId = storyId;
    return this;
  }

  

  /**
  * Get storyId
  * @return storyId
  **/
  @Schema(description = "")
  public UUID getStoryId() {
    return storyId;
  }
  public void setStoryId(UUID storyId) {
    this.storyId = storyId;
  }
  public TrainingMaterial text(String text) {
    this.text = text;
    return this;
  }

  

  /**
  * Get text
  * @return text
  **/
  @Schema(required = true, description = "")
  public String getText() {
    return text;
  }
  public void setText(String text) {
    this.text = text;
  }
  public TrainingMaterial name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  /**
  * Creation time
  * @return createdAt
  **/
  @Schema(description = "Creation time")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }
  /**
  * Last modification time
  * @return modifiedAt
  **/
  @Schema(description = "Last modification time")
  public OffsetDateTime getModifiedAt() {
    return modifiedAt;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrainingMaterial trainingMaterial = (TrainingMaterial) o;
    return Objects.equals(this.id, trainingMaterial.id) &&
        Objects.equals(this.type, trainingMaterial.type) &&
        Objects.equals(this.storyId, trainingMaterial.storyId) &&
        Objects.equals(this.text, trainingMaterial.text) &&
        Objects.equals(this.name, trainingMaterial.name) &&
        Objects.equals(this.createdAt, trainingMaterial.createdAt) &&
        Objects.equals(this.modifiedAt, trainingMaterial.modifiedAt);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, type, storyId, text, name, createdAt, modifiedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrainingMaterial {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    storyId: ").append(toIndentedString(storyId)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
