/*
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fi.metatavu.metamind.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.metatavu.metamind.client.model.VariableType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Variable
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-06T06:22:21.133+03:00[Europe/Helsinki]")public class Variable {

  @JsonProperty("id")

  private UUID id = null;

  @JsonProperty("name")

  private String name = null;

  @JsonProperty("type")

  private VariableType type = null;

  @JsonProperty("storyId")

  private UUID storyId = null;

  @JsonProperty("validationScript")

  private String validationScript = null;

  @JsonProperty("createdAt")

  private OffsetDateTime createdAt = null;

  @JsonProperty("modifiedAt")

  private OffsetDateTime modifiedAt = null;
  /**
  * variable id.
  * @return id
  **/
  @Schema(description = "variable id.")
  public UUID getId() {
    return id;
  }
  public Variable name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public Variable type(VariableType type) {
    this.type = type;
    return this;
  }

  

  /**
  * Get type
  * @return type
  **/
  @Schema(required = true, description = "")
  public VariableType getType() {
    return type;
  }
  public void setType(VariableType type) {
    this.type = type;
  }
  /**
  * Story id
  * @return storyId
  **/
  @Schema(description = "Story id")
  public UUID getStoryId() {
    return storyId;
  }
  public Variable validationScript(String validationScript) {
    this.validationScript = validationScript;
    return this;
  }

  

  /**
  * Validation script
  * @return validationScript
  **/
  @Schema(description = "Validation script")
  public String getValidationScript() {
    return validationScript;
  }
  public void setValidationScript(String validationScript) {
    this.validationScript = validationScript;
  }
  /**
  * Creation time
  * @return createdAt
  **/
  @Schema(description = "Creation time")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }
  /**
  * Last modification time
  * @return modifiedAt
  **/
  @Schema(description = "Last modification time")
  public OffsetDateTime getModifiedAt() {
    return modifiedAt;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Variable variable = (Variable) o;
    return Objects.equals(this.id, variable.id) &&
        Objects.equals(this.name, variable.name) &&
        Objects.equals(this.type, variable.type) &&
        Objects.equals(this.storyId, variable.storyId) &&
        Objects.equals(this.validationScript, variable.validationScript) &&
        Objects.equals(this.createdAt, variable.createdAt) &&
        Objects.equals(this.modifiedAt, variable.modifiedAt);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, name, type, storyId, validationScript, createdAt, modifiedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Variable {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    storyId: ").append(toIndentedString(storyId)).append("\n");
    sb.append("    validationScript: ").append(toIndentedString(validationScript)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
