/**
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MetamindClient) {
      root.MetamindClient = {};
    }
    root.MetamindClient.Script = factory(root.MetamindClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Script model module.
   * @module model/Script
   * @version 0.0.29
   */

  /**
   * Constructs a new <code>Script</code>.
   * @alias module:model/Script
   * @class
   * @param name {String} Script name
   * @param version {String} Script version
   * @param language {String} Script language
   * @param content {String} Script content
   */
  var exports = function(name, version, language, content) {
    var _this = this;

    _this['name'] = name;
    _this['version'] = version;
    _this['language'] = language;
    _this['content'] = content;
  };

  /**
   * Constructs a <code>Script</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Script} obj Optional instance to populate.
   * @return {module:model/Script} The populated <code>Script</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('version')) {
        obj['version'] = ApiClient.convertToType(data['version'], 'String');
      }
      if (data.hasOwnProperty('language')) {
        obj['language'] = ApiClient.convertToType(data['language'], 'String');
      }
      if (data.hasOwnProperty('content')) {
        obj['content'] = ApiClient.convertToType(data['content'], 'String');
      }
    }
    return obj;
  }

  /**
   * Script name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Script version
   * @member {String} version
   */
  exports.prototype['version'] = undefined;
  /**
   * Script language
   * @member {String} language
   */
  exports.prototype['language'] = undefined;
  /**
   * Script content
   * @member {String} content
   */
  exports.prototype['content'] = undefined;



  return exports;
}));


