/**
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IntentType } from './intentType';


export interface ExportedStoryIntent { 
    /**
     * intent id.
     */
    id?: string;
    name: string;
    quickResponse?: string;
    quickResponseOrder: number;
    type: IntentType;
    /**
     * source knot id.
     */
    sourceKnotId?: string;
    /**
     * target knot id.
     */
    targetKnotId: string;
    global: boolean;
    trainingMaterialIds?: Array<string>;
}
export interface ExportedStoryIntentOpt { 
    /**
     * intent id.
     */
    id?: string;
    name?: string;
    quickResponse?: string;
    quickResponseOrder?: number;
    type?: IntentType;
    /**
     * source knot id.
     */
    sourceKnotId?: string;
    /**
     * target knot id.
     */
    targetKnotId?: string;
    global?: boolean;
    trainingMaterialIds?: Array<string>;
}
