/**
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { VariableType } from './variableType';


export interface ExportedStoryVariable { 
    name: string;
    type: VariableType;
    /**
     * Validation script
     */
    validationScript?: string;
}
export interface ExportedStoryVariableOpt { 
    name?: string;
    type?: VariableType;
    /**
     * Validation script
     */
    validationScript?: string;
}
