/**
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ExportedStoryScript { 
    /**
     * Script name
     */
    name: string;
    /**
     * Script version
     */
    version: string;
    /**
     * Script language
     */
    language: string;
    /**
     * Script content
     */
    content: string;
}
export interface ExportedStoryScriptOpt { 
    /**
     * Script name
     */
    name?: string;
    /**
     * Script version
     */
    version?: string;
    /**
     * Script language
     */
    language?: string;
    /**
     * Script content
     */
    content?: string;
}
