/**
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExportedStoryIntent } from './exportedStoryIntent';
import { ExportedStoryKnot } from './exportedStoryKnot';
import { ExportedStoryScript } from './exportedStoryScript';
import { ExportedStoryTrainingMaterial } from './exportedStoryTrainingMaterial';
import { ExportedStoryVariable } from './exportedStoryVariable';


export interface ExportedStory { 
    /**
     * Story name.
     */
    name: string;
    /**
     * Default hint.
     */
    defaultHint?: string;
    /**
     * Story locale.
     */
    locale: string;
    knots: Array<ExportedStoryKnot>;
    variables: Array<ExportedStoryVariable>;
    scripts: Array<ExportedStoryScript>;
    intents: Array<ExportedStoryIntent>;
    trainingMaterials: Array<ExportedStoryTrainingMaterial>;
}
export interface ExportedStoryOpt { 
    /**
     * Story name.
     */
    name?: string;
    /**
     * Default hint.
     */
    defaultHint?: string;
    /**
     * Story locale.
     */
    locale?: string;
    knots?: Array<ExportedStoryKnot>;
    variables?: Array<ExportedStoryVariable>;
    scripts?: Array<ExportedStoryScript>;
    intents?: Array<ExportedStoryIntent>;
    trainingMaterials?: Array<ExportedStoryTrainingMaterial>;
}
