/**
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type IntentType = 'NORMAL' | 'CONFUSED' | 'REDIRECT' | 'DEFAULT';

export const IntentType = {
    NORMAL: 'NORMAL' as IntentType,
    CONFUSED: 'CONFUSED' as IntentType,
    REDIRECT: 'REDIRECT' as IntentType,
    DEFAULT: 'DEFAULT' as IntentType
};
