/**
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type IntentType = 'OPENNLP' | 'TEMPLATE' | 'CONFUSED' | 'REDIRECT';

export const IntentType = {
    OPENNLP: 'OPENNLP' as IntentType,
    TEMPLATE: 'TEMPLATE' as IntentType,
    CONFUSED: 'CONFUSED' as IntentType,
    REDIRECT: 'REDIRECT' as IntentType
};
