/**
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Coordinates } from './coordinates';
import { KnotType } from './knotType';
import { TokenizerType } from './tokenizerType';


export interface Knot { 
    /**
     * knot id.
     */
    readonly id?: string;
    type: KnotType;
    tokenizer: TokenizerType;
    name: string;
    content: string;
    hint?: string;
    /**
     * Story id
     */
    readonly storyId?: string;
    coordinates?: Coordinates;
    /**
     * Creation time
     */
    readonly createdAt?: Date;
    /**
     * Last modification time
     */
    readonly modifiedAt?: Date;
}
export interface KnotOpt { 
    /**
     * knot id.
     */
    readonly id?: string;
    type?: KnotType;
    tokenizer?: TokenizerType;
    name?: string;
    content?: string;
    hint?: string;
    /**
     * Story id
     */
    readonly storyId?: string;
    coordinates?: Coordinates;
    /**
     * Creation time
     */
    readonly createdAt?: Date;
    /**
     * Last modification time
     */
    readonly modifiedAt?: Date;
}
