/**
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Message { 
    /**
     * Message id
     */
    readonly id?: string;
    /**
     * Session id the message belongs to
     */
    sessionId: string;
    /**
     * Message content
     */
    content: string;
    /**
     * Response text. Used only when responding
     */
    readonly response?: Array<string>;
    /**
     * Hint text. Used only when responding
     */
    readonly hint?: string;
    /**
     * List of quick responses. Used only when responding
     */
    readonly quickResponses?: Array<string>;
    /**
     * Value how confident the bot was about the intent
     */
    readonly confidence?: number;
    /**
     * source knot id id.
     */
    readonly sourceKnotId: string;
    /**
     * matched intent id. Null if intent not found
     */
    readonly matchedIntentId?: string;
    /**
     * Creation time
     */
    readonly createdAt?: Date;
    /**
     * Last modification time
     */
    readonly modifiedAt?: Date;
}
export interface MessageOpt { 
    /**
     * Message id
     */
    readonly id?: string;
    /**
     * Session id the message belongs to
     */
    sessionId?: string;
    /**
     * Message content
     */
    content?: string;
    /**
     * Response text. Used only when responding
     */
    readonly response?: Array<string>;
    /**
     * Hint text. Used only when responding
     */
    readonly hint?: string;
    /**
     * List of quick responses. Used only when responding
     */
    readonly quickResponses?: Array<string>;
    /**
     * Value how confident the bot was about the intent
     */
    readonly confidence?: number;
    /**
     * source knot id id.
     */
    readonly sourceKnotId?: string;
    /**
     * matched intent id. Null if intent not found
     */
    readonly matchedIntentId?: string;
    /**
     * Creation time
     */
    readonly createdAt?: Date;
    /**
     * Last modification time
     */
    readonly modifiedAt?: Date;
}
