/**
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Session { 
    /**
     * Session id.
     */
    readonly id?: string;
    /**
     * Session locale
     */
    locale: string;
    /**
     * Session time zone
     */
    timeZone: string;
    /**
     * Visitor details
     */
    visitor: string;
    /**
     * Story id
     */
    readonly storyId?: string;
    /**
     * Creation time
     */
    readonly createdAt?: Date;
    /**
     * Last modification time
     */
    readonly modifiedAt?: Date;
}
export interface SessionOpt { 
    /**
     * Session id.
     */
    readonly id?: string;
    /**
     * Session locale
     */
    locale?: string;
    /**
     * Session time zone
     */
    timeZone?: string;
    /**
     * Visitor details
     */
    visitor?: string;
    /**
     * Story id
     */
    readonly storyId?: string;
    /**
     * Creation time
     */
    readonly createdAt?: Date;
    /**
     * Last modification time
     */
    readonly modifiedAt?: Date;
}
