/**
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type TokenizerType = 'WHITESPACE' | 'UNTOKENIZED';

export const TokenizerType = {
    WHITESPACE: 'WHITESPACE' as TokenizerType,
    UNTOKENIZED: 'UNTOKENIZED' as TokenizerType
};
