/**
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TrainingMaterial { 
    /**
     * intent id.
     */
    readonly id?: string;
    storyId?: string;
    text: string;
    name: string;
    /**
     * Creation time
     */
    readonly createdAt?: Date;
    /**
     * Last modification time
     */
    readonly modifiedAt?: Date;
}
export interface TrainingMaterialOpt { 
    /**
     * intent id.
     */
    readonly id?: string;
    storyId?: string;
    text?: string;
    name?: string;
    /**
     * Creation time
     */
    readonly createdAt?: Date;
    /**
     * Last modification time
     */
    readonly modifiedAt?: Date;
}
