/**
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type TrainingMaterialType = 'INTENTREGEX' | 'VARIABLEOPENNLPNER' | 'INTENTOPENNLPDOCCAT';

export const TrainingMaterialType = {
    INTENTREGEX: 'INTENTREGEX' as TrainingMaterialType,
    VARIABLEOPENNLPNER: 'VARIABLEOPENNLPNER' as TrainingMaterialType,
    INTENTOPENNLPDOCCAT: 'INTENTOPENNLPDOCCAT' as TrainingMaterialType
};
