/**
 * Metamind API
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type VariableType = 'STRING' | 'NUMBER';

export const VariableType = {
    STRING: 'STRING' as VariableType,
    NUMBER: 'NUMBER' as VariableType
};
